project:
  type: website
  # The `output-dir` has to match what's set up on
  # Github. It's under 
  # repo Settings
  #   >> Pages
  #   >> Buld and deployment
  output-dir: gp_site

website:
  title: "quarto-github-pages-experiment"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



