project:
  type: website
  #
  # The `output-dir` has to match what's set up on
  # Github. It's under 
  # repo Settings
  #   >> Pages
  #   >> Buld and deployment
  #
  # only available options seems to be '/' and '/docs'
  output-dir: docs

website:
  title: "quarto-github-pages-experiment"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      dark: [flatly, .quarto/darkly.scss]
    css: styles.css
    toc: true



