project:
  type: website
  output-dir: docs # Github Pages looks here

website:
  title: "quarto-github-pages-experiment"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



